version: '3.9'

services:

    web:
        build:
            context: ../
            dockerfile: docker/Dockerfile
            target: web
        restart: always
        env_file:
            - ../.env
        volumes:
            - $PUBLIC_DIRECTORY_VOLUME:$PUBLIC_DIRECTORY
            - $SOURCE_DIRECTORY_VOLUME:$SOURCE_DIRECTORY
        labels:
            - traefik.enable=true
            - traefik.http.routers.$TRAEFIK_RESOLVER.rule=Host(`$HOST`)
            - traefik.http.routers.$TRAEFIK_RESOLVER.entrypoints=websecure
            - traefik.http.routers.$TRAEFIK_RESOLVER.tls=true
            - traefik.http.routers.$TRAEFIK_RESOLVER.tls.certresolver=myresolver
            - traefik.http.routers.$TRAEFIK_RESOLVER.tls.options=mintls12@file
